# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for CoverUP PDF (Windows + macOS desktop builds).

Build from the repo root:

    pyinstaller packaging/coverup.spec --noconfirm

Design decisions (see packaging/README.md):
  - ONEDIR layout (fast startup, easy to inspect, required for the .app bundle)
  - console=False (GUI app), upx=False (AV false positives / codesign issues)
  - target_arch=None: each build is native to the runner arch. There is NO
    universal2 macOS build because pypdfium2 and Pillow do not ship
    universal2 wheels; we build arm64 and x86_64 separately in CI.
  - Version is parsed from coverup/__init__.py so the bundle metadata always
    matches the package version.
"""

import os
import re
import sys

from PyInstaller.utils.hooks import collect_all, collect_data_files

# The spec lives in packaging/, so the repo root is its parent directory.
# SPECPATH is provided by PyInstaller as the directory containing this file.
REPO_ROOT = os.path.abspath(os.path.join(SPECPATH, os.pardir))  # noqa: F821

APP_NAME = 'CoverUP'
BUNDLE_ID = 'de.digidigital.coverup'


def _read_version():
    """Parse __version__ from coverup/__init__.py without importing it."""
    init_path = os.path.join(REPO_ROOT, 'coverup', '__init__.py')
    with open(init_path, encoding='utf-8') as fh:
        match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', fh.read(), re.M)
    if not match:
        raise SystemExit(f'Could not parse __version__ from {init_path}')
    return match.group(1)


VERSION = _read_version()

# ---------------------------------------------------------------------------
# Dependency collection
# ---------------------------------------------------------------------------
# The coverup package ships its own PyInstaller hook (coverup/pyinstaller_hooks/
# hook-coverup.py, registered via the pyinstaller40 entry point) which collects
# the fonts. Everything below is belt-and-braces for third-party packages
# whose data files PyInstaller's bundled hooks may miss.

datas = []
binaries = []
hiddenimports = [
    'PIL._tkinter_finder',   # Pillow <-> tkinter bridge (dynamic import)
    'lxml._elementpath',     # imported from C code in lxml (python-docx dep)
]

# pypdfium2's native library lives in the separate pypdfium2_raw package.
raw_datas, raw_binaries, raw_hiddenimports = collect_all('pypdfium2_raw')
datas += raw_datas
binaries += raw_binaries
hiddenimports += raw_hiddenimports

# Packages that ship data files (font metrics, CMaps, certs, templates, ...).
for pkg in ('fpdf', 'docx', 'pdfminer', 'pyhanko', 'pyhanko_certvalidator'):
    datas += collect_data_files(pkg)

# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

a = Analysis(
    [os.path.join(REPO_ROOT, 'CoverUP.py')],
    pathex=[REPO_ROOT],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'numpy',
        'setuptools',
        'pip',
        'wheel',
        'pydoc_data',
        'lib2to3',
        'test',
        'unittest',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

# Platform icon: .ico on Windows, .icns on macOS (generated by
# packaging/macos/make_icns.sh from CoverUP.svg).
if sys.platform == 'darwin':
    icon_file = os.path.join(REPO_ROOT, 'packaging', 'macos', 'CoverUP.icns')
elif sys.platform == 'win32':
    icon_file = os.path.join(REPO_ROOT, 'CoverUP.ico')
else:
    icon_file = None

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,   # native arch of the build machine; no universal2
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_file,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name=APP_NAME,
)

# ---------------------------------------------------------------------------
# macOS .app bundle
# ---------------------------------------------------------------------------

if sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name=f'{APP_NAME}.app',
        icon=icon_file,
        bundle_identifier=BUNDLE_ID,
        version=VERSION,
        info_plist={
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleShortVersionString': VERSION,
            'CFBundleVersion': VERSION,
            'NSHighResolutionCapable': True,
            'LSMinimumSystemVersion': '13.0',
            'LSApplicationCategoryType': 'public.app-category.productivity',
            'NSHumanReadableCopyright': '(c) digidigital. GPL-3.0.',
            'CFBundleDocumentTypes': [
                {
                    'CFBundleTypeName': 'PDF Document',
                    'CFBundleTypeRole': 'Viewer',
                    'LSHandlerRank': 'Alternate',
                    'LSItemContentTypes': ['com.adobe.pdf'],
                },
                {
                    'CFBundleTypeName': 'PNG Image',
                    'CFBundleTypeRole': 'Viewer',
                    'LSHandlerRank': 'Alternate',
                    'LSItemContentTypes': ['public.png'],
                },
                {
                    'CFBundleTypeName': 'JPEG Image',
                    'CFBundleTypeRole': 'Viewer',
                    'LSHandlerRank': 'Alternate',
                    'LSItemContentTypes': ['public.jpeg'],
                },
            ],
        },
    )
